import { generateSEO } from '@/config/seo/seo'
import React from 'react'
import PrimaryButton from '../components/reusables/buttons/PrimaryButton'
import Image from 'next/image'
import Heading from '../components/reusables/contents/Heading'
import { auth, signOut } from '@/auth'
import Link from 'next/link'
import Container from '@/components/reusables/contents/Container'
import H1 from '@/components/reusables/contents/elements/H1'
import CustomCalender from '@/components/reusables/CustomCalender'
import { SunIcon } from 'lucide-react'
import Img from '@/components/reusables/contents/elements/Img'
export const metadata = generateSEO({
  title: 'Page - Next.js',
  description: 'Generated by Next.js',
  openGraph: {

  }
})
const page = async () => {
  const session = await auth()
  return (
    <div className='relative mt-[-44px] min-h-screen bg-white dark:bg-black py-12 md:py-16   '>
      <Container>
        <div className="flex-center flex-col gap-y-4 ">
          <Heading align='text-center' parts={[{ text: 'Next.Js Starter', isSpan: true, spanClassName: 'text-paragraphrimary' }, { text: 'Template' }]} subTitle='Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, accusantium consectetur neque nulla deserunt distinctio a unde, animi tempora quisquam laborum. Vero expedita rerum neque? Quos ullam reprehenderit animi ipsa.' />
          <PrimaryButton isOutlineAnimation className="mt-4">Get Started</PrimaryButton>
          {session?.user ? <><p>hello {session?.user?.email}</p>
            <form action={async () => {
              "use server"
              await signOut()
            }}><button>Logout</button></form>

          </> : <Link href={'/api/auth/signin'}>Login</Link>}
          <CustomCalender/>
          <h1 className='icon-box-shadow p-4' p-4>How it workssss?</h1>
          

          <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iste rem consequatur perferendis inventore nemo maxime neque necessitatibus non. Illo asperiores deserunt delectus placeat ipsa veniam iste molestias illum adipisci architecto!</p>
        </div>

      </Container>
    </div>
  )
}


export default page