import { generateSEO } from '@/config/seo/seo'
import React from 'react'
import PrimaryButton from '../components/reusables/buttons/PrimaryButton'
import Image from 'next/image'
import Heading from '../components/reusables/contents/Heading'
import { auth, signOut } from '@/auth'
import Link from 'next/link'
import Container from '@/components/reusables/contents/Container'
export const metadata = generateSEO({
  title: 'Page - Next.js',
  description: 'Generated by Next.js',
  openGraph: {

  }
})
const page = async () => {
  const session = await auth()
  return (
    <div className='mt-[-44px] min-h-screen py-12 md:py-16 bg-gray-50 dark:bg-[#201717]  '>
      <Container>
        <div className="flex-center flex-col gap-y-4">
          <Heading align='text-center' parts={[{ text: 'Next.Js Starter', isSpan: true, spanClassName: 'text-primary' }, { text: 'Template' }]} subTitle='Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, accusantium consectetur neque nulla deserunt distinctio a unde, animi tempora quisquam laborum. Vero expedita rerum neque? Quos ullam reprehenderit animi ipsa.' />
          <PrimaryButton isOutlineAnimation className="mt-4">Get Started</PrimaryButton>
          {session?.user ? <><p>hello {session?.user?.email}</p>
            <form action={async () => {
              "use server"
              await signOut()
            }}><button>Logout</button></form>

          </> : <Link href={'/api/auth/signin'}>Login</Link>}
        </div>

      </Container>
    </div>
  )
}


export default page