# Use the official Node.js image as a base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the app dependencies
RUN npm install --production

# Copy all other files to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 3002

# Command to run the app
CMD ["npm", "run","production"]
